version: '3'

services:

# furst.io

  furst:
    image: nginx:latest
    container_name: furst.io
    volumes:
      - ${DOCKER}/websites/furst.io:/usr/share/nginx/html:ro
    labels:
      - traefik.enable=true
      - traefik.backend=furst
      - 'traefik.frontend.rule=Host:${DOMAIN}, www.${DOMAIN}'
      - traefik.docker.network=traefik
      - traefik.port=80
    networks:
      - traefik
    restart: on-failure

# highpulp.co

  highpulp:
    image: nginx:latest
    container_name: highpulp.co
    volumes:
      - ${DOCKER}/websites/highpulp.co:/usr/share/nginx/html:ro
    labels:
      - traefik.enable=true
      - traefik.backend=highpulp
      - traefik.domain=highpulp.co
      - 'traefik.frontend.rule=Host:highpulp.co'
      - traefik.docker.network=traefik
      - traefik.port=80
    networks:
      - traefik
    restart: on-failure

# MariaDB

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    volumes:
      - $NAS/.mariadb/data:/var/lib/mysql
      - $NAS/.mariadb/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: mysqladmin ping -h localhost || exit 1
      interval: 60s
      timeout: 10s
      retries: 5
    environment:
      - MYSQL_ROOT_PASSWORD=${SQL_ROOT}
      - TZ=${TZ}
    networks:
      - database
    ports:
      - 3306:3306
    restart: on-failure

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - 8181:8080
    networks:
      - database

# WordPress

  wordpress:
    image: bitnami/wordpress:latest
    container_name: wordpress
    volumes:
      - $NAS/.wordpress:/bitnami
    environment:
      - WORDPRESS_DATABASE_USER=wordpress
      - WORDPRESS_DATABASE_NAME=wordpress
      - WORDPRESS_DATABASE_PASSWORD=${SQL_PASSWORD}
    links:
      - mariadb
    labels:
      - traefik.enable=true
      - traefik.backend=wordpress
      - 'traefik.frontend.rule=Host:blog.furst.io'
      - traefik.docker.network=traefik
      - traefik.port=80
    networks:
      - database
      - traefik

# Bookstack

  bookstack:
    image: solidnerd/bookstack
    container_name: bookstack
    depends_on:
      - mariadb
    environment:
      - DB_HOST=mariadb:3306
      - DB_DATABASE=bookstack
      - DB_USERNAME=bookstack
      - DB_PASSWORD=${SQL_PASSWORD}
    volumes:
      - $NAS/.bookstack/uploads:/var/www/bookstack/public/uploads
      - $NAS/.bookstack/storage-uploads:/var/www/bookstack/public/storage-uploads
    labels:
      - traefik.enable=true
      - traefik.backend=bookstack
      - 'traefik.frontend.rule=Host:bookstack.${DOMAIN}'
      - traefik.docker.network=traefik
      - traefik.port=80
    networks:
      - traefik
      - database
    restart: always

# Nextcloud:

  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    hostname: nextcloud
    volumes:
      - $NAS/.nextcloud/data:/var/www/html/data
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${SQL_PASSWORD}
      - MYSQL_HOST=mariadb
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=${SQL_PASSWORD}
    labels:
      - traefik.enable=true
      - traefik.backend=nextcloud
      - 'traefik.frontend.rule=Host:nextcloud.${DOMAIN}'
      - traefik.docker.network=traefik
      - traefik.port=80
    networks:
      - database
      - traefik
    depends_on:
      - mariadb
    restart: on-failure

# Chevereto

  chevereto:
    container_name: chevereto
    image: nmtan/chevereto
    environment:
      - GUID=${PGID}
      - UUID=${PUID}
      - CHEVERETO_DB_HOST=mariadb
      - CHEVERETO_DB_USERNAME=chevereto
      - CHEVERETO_DB_PASSWORD=${SQL_PASSWORD}
      - CHEVERETO_DB_NAME=chevereto
      - CHEVERETO_DB_PREFIX=chv_
    volumes:
      - $NAS/.chevereto/images:/var/www/html/images:rw
    labels:
      - traefik.enable=true
      - traefik.backend=chevereto
      - 'traefik.frontend.rule=Host:i.${DOMAIN}'
      - traefik.docker.network=traefik
      - traefik.port=80
    networks:
      - database
      - traefik
    depends_on:
      - mariadb
    restart: unless-stopped

# GitLab

  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce
    volumes:
      - $NAS/.gitlab/config:/etc/config
      - $NAS/.gitlab/logs:/var/log/gitlab
      - $NAS/.gitlab/data:/var/opt/gitlab
    labels:
      - traefik.enable=true
      - traefik.backend=gitlab
      - 'traefik.frontend.rule=Host:git.${DOMAIN}'
      - traefik.docker.network=traefik
      - traefik.port=80
    networks:
      - default
      - traefik
    restart: unless-stopped

networks:
  traefik:
    external: true
  database:
    external: true
